### PR TITLE
fix status of a few more tests in core-elements

### PR DESCRIPTION
**Pull request by sigmundch**
@jakemac53

### CODE REVIEW

**Comment by jakemac53** [comment]
lgtm, these are passing now?

**Comment by sigmundch** [comment]
yeah, they seem to be failing before because of the package-root thing. Here is an example log: http://chromegw.corp.google.com/i/client.dart.packages/builders/packages-linux-core-elements/builds/356/steps/Test%20dartium%20under%20build/logs/stdio

**Comment by jakemac53** [comment]
cool! that explains a lot haha :)

**Comment by sigmundch** [comment]
not sure why there are still a couple left behind though :(

**Pull request merged**
